version: 1.0.{build}

platform: Any CPU

configuration: Release

environment:
  dynamo_solution: src/Dynamo.All.2013.sln
  xmlDocs_solution: tools/XmlDocToMarkdown/XmlDocToMarkdown.sln
  access_token:
    secure:CtV9XcQ8dUwJoI5XvZS21wl/S72lgnBB0k1eK5GAjseS6Z33uuvLALxVFAq6IqLT
build_script:
  - msbuild %dynamo_solution%
  - msbuild %xmlDocs_solution%

after_build:
  - ps: tools/XmlDocToMarkdown/XmlDocToMarkdown/BuildScript/BuildScript.ps1

on_success:  
 - ps: >- 
    if($env:APPVEYOR_PULL_REQUEST_NUMBER -eq '') {	
      git config --global user.name $env:APPVEYOR_REPO_COMMIT_AUTHOR
      git config --global credential.helper store
      Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n" 
      git clone https://DynamoDS:$($env:access_token)@github.com/DynamoDS/DynamoAPI.git  
      tools/XmlDocToMarkdown/XmlDocToMarkdown/BuildScript/PublishDocs.ps1	
    }  
  
test: off